using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
public class Main : MonoBehaviour
{
    public InSelect inSelect;
    public InDC inDC;
    public ExPanel exPanel;
    public InRC inRC;
    public ProCreateNode proCreateNode;
    public InMouse inMouse;
    public ProTryConn proTryConn;
    public ProCreateConn proCreateConn;
    public InDelete inDelete;
    public ProDeleteNode proDeleteNode;
    public DBGet dBGet;
    public DB dB;
    public DBSet dBSet;
    public DBDel dBDel;
    public DBCrt dBCrt;
    public InRename inRename;
    public InMove inMove;
    public ProRename proRename;
    public ProMove proMove;
    public InExport inExport;
    public ProExport proExport;
    public DBRes dBRes;
    public OutCreateConn outCreateConn;
    public OutCreateNode outCreateNode;
    public OutRename outRename;
    public OutMove outMove;
    public OutExport outExport;
    public OutDelete outDelete;
    public ProCreateInter proCreateInter;
    public OutCreateInter outCreateInter;
    public InSave inSave;
    public ProSave proSave;
    public OutSave outSave;
    public InLoad inLoad;
    public ProLoad proLoad;
    public OutLoad outLoad;
    void Start()
    {
        // Application
        Application.targetFrameRate = 60;

        // High IQ
        inSave.save = proSave.Save;
        proSave.get = dBGet.GetInDbgrReceiver();
        proSave.save = outSave.Save;
        inLoad.load = proLoad.Load;
        proLoad.load = outLoad.Load;
        proLoad.crtNode = proCreateNode.GetIniReceiver();
        proLoad.crtConn = proCreateConn.GetIciReceiver();
        proLoad.crtInter = proCreateInter.GetIiiReceiver();
        proLoad.rename = proRename.GetPriReceiver();
        proLoad.get = dBGet.GetInDbgrReceiver();
        proLoad.del = proDeleteNode.GetIdiReceiver();

        // Low IQ
        IInDCToExPanelSender inDCToExPanelSender = inDC;
        IInDCToExPanelReceiver inDCToExPanelReceiver = exPanel;
        inDCToExPanelSender.AddDcPosReceiver(inDCToExPanelReceiver.GetDcPosReceiver());
        IInRCToExPanelSender inRCToExPanelSender = inRC;
        IInRCToExPanelReceiver inRCToExPanelReceiver = exPanel;
        inRCToExPanelSender.AddRcPosReceiver(inRCToExPanelReceiver.GetRcPosReceiver());
        IInSelectToExPanelSender inSelectToExPanelSender = inSelect;
        IInSelectToExPanelReceiver inSelectToExPanelReceiver = exPanel;
        inSelectToExPanelSender.AddSiReceiver(inSelectToExPanelReceiver.GetSiReceiver());
        IExPanelToProCreateNodeSender exPanelToProCreateNodeSender = exPanel;
        IExPanelToProCreateNodeReceiver exPanelToProCreateNodeReceiver = proCreateNode;
        exPanelToProCreateNodeSender.AddIniReceiver(exPanelToProCreateNodeReceiver.GetIniReceiver());
        IInMouseToExPanelSender inMouseToExPanelSender = inMouse;
        IInMouseToExPanelReceiver inMouseToExPanelReceiver = exPanel;
        inMouseToExPanelSender.AddMousePosReceiver(inMouseToExPanelReceiver.GetMousePosReceiver());
        IExPanelToProTryConnSender exPanelToProTryConnSender = exPanel;
        IExPanelToProTryConnReceiver exPanelToProTryConnReceiver = proTryConn;
        exPanelToProTryConnSender.AddTciReceiver(exPanelToProTryConnReceiver.GetTciReceiver());
        IExPanelToProCreateConnSender exPanelToProCreateConnSender = exPanel;
        IExPanelToProCreateConnReceiver exPanelToProCreateConnReceiver = proCreateConn;
        exPanelToProCreateConnSender.AddIciReceiver(exPanelToProCreateConnReceiver.GetIciReceiver());
        IInDeleteToExPanelSender inDeleteToExPanelSender = inDelete;
        IInDeleteToExPanelReceiver inDeleteToExPanelReceiver = exPanel;
        inDeleteToExPanelSender.AddDeletePosReceiver(inDeleteToExPanelReceiver.GetDeletePosReceiver());
        IExPanelToProDeleteNodeSender exPanelToProDeleteNodeSender = exPanel;
        IExPanelToProDeleteNodeReceiver exPanelToProDeleteNodeReceiver = proDeleteNode;
        exPanelToProDeleteNodeSender.AddIdiReceiver(exPanelToProDeleteNodeReceiver.GetIdiReceiver());
        IDBGetToDBSender dBGetToDBSender = dBGet;
        IDBGetToDBReceiver dBGetToDBReceiver = dB;
        dBGetToDBSender.AddOutDbgrReceiver(dBGetToDBReceiver.GetOutDbgrReceiver());
        IDBSetToDBSender dBSetToDBSender = dBSet;
        IDBSetToDBReceiver dBSetToDBReceiver = dB;
        dBSetToDBSender.AddOutDbsrReceiver(dBSetToDBReceiver.GetOutDbsrReceiver());
        IDBDelToDBSender dBDelToDBSender = dBDel;
        IDBDelToDBReceiver dBDelToDBReceiver = dB;
        dBDelToDBSender.AddOutDbdrReceiver(dBDelToDBReceiver.GetOutDbdrReceiver());
        IDBCrtToDBSender dBCrtToDBSender = dBCrt;
        IDBCrtToDBReceiver dBCrtToDBReceiver = dB;
        dBCrtToDBSender.AddOutDbcrReceiver(dBCrtToDBReceiver.GetOutDbcrReceiver());
        IInRenameToProRenameSender inRenameToProRenameSender = inRename;
        IInRenameToProRenameReceiver inRenameToProRenameReceiver = proRename;
        inRenameToProRenameSender.AddPriReceiver(inRenameToProRenameReceiver.GetPriReceiver());
        IInMoveToProMoveSender inMoveToProMoveSender = inMove;
        IInMoveToProMoveReceiver inMoveToProMoveReceiver = proMove;
        inMoveToProMoveSender.AddPmiReceiver(inMoveToProMoveReceiver.GetPmiReceiver());
        IInExportToProExportSender inExportToProExportSender = inExport;
        IInExportToProExportReceiver inExportToProExportReceiver = proExport;
        inExportToProExportSender.AddPeiReceiver(inExportToProExportReceiver.GetPeiReceiver());
        IDBToDBResSender dBToDBResSender = dB;
        IDBToDBResReceiver dBToDBResReceiver = dBRes;
        dBToDBResSender.AddInDbgrReceiver(dBToDBResReceiver.GetInDbgrReceiver());
        IDBCrter proCreateNodeToDBCrtSender = proCreateNode;
        IDBCrt proCreateNodeToDBCrtReceiver = dBCrt;
        proCreateNodeToDBCrtSender.AddInDbcrReceiver(proCreateNodeToDBCrtReceiver.GetInDbcrReceiver());
        IProRenameToDBSetSender proRenameToDBSetSender = proRename;
        IDBSet proRenameToDBSetReceiver = dBSet;
        proRenameToDBSetSender.AddInDbsrReceiver(proRenameToDBSetReceiver.GetInDbsrReceiver());
        IProMoveToDBSetSender proMoveToDBSetSender = proMove;
        IDBSet proMoveToDBSetReceiver = dBSet;
        proMoveToDBSetSender.AddInDbsrReceiver(proMoveToDBSetReceiver.GetInDbsrReceiver());
        IProDeleteNodeToDBDelSender proDeleteNodeToDBDelSender = proDeleteNode;
        IProDeleteNodeToDBDelReceiver proDeleteNodeToDBDelReceiver = dBDel;
        proDeleteNodeToDBDelSender.AddInDbdrReceiver(proDeleteNodeToDBDelReceiver.GetInDbdrReceiver());
        IDBGetter proExportToDBGetSender = proExport;
        IDBGet proExportToDBGetReceiver = dBGet;
        proExportToDBGetSender.AddInDbgrReceiver(proExportToDBGetReceiver.GetInDbgrReceiver());
        IDBCrter proCreateConnToDBCrtSender = proCreateConn;
        IDBCrt proCreateConnToDBCrtReceiver = dBCrt;
        proCreateConnToDBCrtSender.AddInDbcrReceiver(proCreateConnToDBCrtReceiver.GetInDbcrReceiver());
        proCreateInter.AddInDbcrReceiver(dBCrt.GetInDbcrReceiver());
        IDBGetter proDeleteNodeToDBGetSender = proDeleteNode;
        IDBGet proDeleteNodeToDBGetReceiver = dBGet;
        proDeleteNodeToDBGetSender.AddInDbgrReceiver(proDeleteNodeToDBGetReceiver.GetInDbgrReceiver());
        IDBGetter proCreateNodeToDBGetSender = proCreateNode;
        IDBGet proCreateNodeToDBGetReceiver = dBGet;
        proCreateNodeToDBGetSender.AddInDbgrReceiver(proCreateNodeToDBGetReceiver.GetInDbgrReceiver());
        IDBGetter proCreateConnToDBGetSender = proCreateConn;
        IDBGet proCreateConnToDBGetReceiver = dBGet;
        proCreateConnToDBGetSender.AddInDbgrReceiver(proCreateConnToDBGetReceiver.GetInDbgrReceiver());
        IDBGetter proRenameToDBGetSender = proRename;
        IDBGet proRenameToDBGetReceiver = dBGet;
        proRenameToDBGetSender.AddInDbgrReceiver(proRenameToDBGetReceiver.GetInDbgrReceiver());
        IDBGetter proMoveToDBGetSender = proMove;
        IDBGet proMoveToDBGetReceiver = dBGet;
        proMoveToDBGetSender.AddInDbgrReceiver(proMoveToDBGetReceiver.GetInDbgrReceiver());
        IProCreateConnToOutCreateConnSender proCreateConnToOutCreateConnSender = proCreateConn;
        IProCreateConnToOutCreateConnReceiver proCreateConnToOutCreateConnReceiver = outCreateConn;
        proCreateConnToOutCreateConnSender.AddFciReceiver(proCreateConnToOutCreateConnReceiver.GetFciReceiver());
        IProCreateNodeToOutCreateNodeSender proCreateNodeToOutCreateNodeSender = proCreateNode;
        IProCreateNodeToOutCreateNodeReceiver proCreateNodeToOutCreateNodeReceiver = outCreateNode;
        proCreateNodeToOutCreateNodeSender.AddFniReceiver(proCreateNodeToOutCreateNodeReceiver.GetFniReceiver());
        IProRenameToOutRenameSender proRenameToOutRenameSender = proRename;
        IProRenameToOutRenameReceiver proRenameToOutRenameReceiver = outRename;
        proRenameToOutRenameSender.AddFriReceiver(proRenameToOutRenameReceiver.GetFriReceiver());
        IProMoveToOutMoveSender proMoveToOutMoveSender = proMove;
        IProMoveToOutMoveReceiver proMoveToOutMoveReceiver = outMove;
        proMoveToOutMoveSender.AddFmiReceiver(proMoveToOutMoveReceiver.GetFmiReceiver());
        IProExportToOutExportSender proExportToOutExportSender = proExport;
        IProExportToOutExportReceiver proExportToOutExportReceiver = outExport;
        proExportToOutExportSender.AddFeiReceiver(proExportToOutExportReceiver.GetFeiReceiver());
        IProDeleteNodeToOutDeleteSender proDeleteNodeToOutDeleteSender = proDeleteNode;
        IProDeleteNodeToOutDeleteReceiver proDeleteNodeToOutDeleteReceiver = outDelete;
        proDeleteNodeToOutDeleteSender.AddFdiReceiver(proDeleteNodeToOutDeleteReceiver.GetFdiReceiver());
        IExPanelToProCreateInterSender exPanelToProCreateInterSender = exPanel;
        IExPanelToProCreateInterReceiver exPanelToProCreateInterReceiver = proCreateInter;
        exPanelToProCreateInterSender.AddIiiReceiver(exPanelToProCreateInterReceiver.GetIiiReceiver());
        IProCreateInterToOutCreateInterSender proCreateInterToOutCreateInterSender = proCreateInter;
        IProCreateInterToOutCreateInterReceiver proCreateInterToOutCreateInterReceiver = outCreateInter;
        proCreateInterToOutCreateInterSender.AddFiiReceiver(proCreateInterToOutCreateInterReceiver.GetFiiReceiver());
        IDBGetter proCreateInterToDBGetSender = proCreateInter;
        IDBGet proCreateInterToDBGetReceiver = dBGet;
        proCreateInterToDBGetSender.AddInDbgrReceiver(proCreateInterToDBGetReceiver.GetInDbgrReceiver());
        exPanel.AddInDbgrReceiver(dBGet.GetInDbgrReceiver());
    }
}
